version: '3'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/db/mongodb:/data/base

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /opt/db/elasticsearch:/data/base
    ports:
      - 9200:9200
      - 9300:9300

  searcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi
    container_name: searcher
    restart: always
    tty: True
    ports:
      - 8000:8000
